name: Deploy

on:
  push:
    branches: [master]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build React App
        run: REACT_APP_BASE_URL=test yarn build
  deploy:
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./build